package grupo65universidad.Vistas;

import grupo65universidad.AccesoADatos.AlumnoDAO;
import grupo65universidad.AccesoADatos.InscripcionDAO;
import grupo65universidad.Entidades.Alumno;
import grupo65universidad.Entidades.Materia;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

public class Inscripciones extends javax.swing.JInternalFrame {

    private Alumno selectedAlumno = null;
    private int idMateria = 0;
    private int idAlumno = 0;

    private DefaultTableModel modelo = new DefaultTableModel() {

        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };

    /**
     * Creates new form Inscripciones
     */
    public Inscripciones() {
        initComponents();
        armarCabecera();
        jRBMNoInscriptas.setSelected(true);

        // Agregar el ListSelectionListener aquí------- // Agrega un oyente de eventos de mouse a la tabla dando 1 Click
        //o 2 click --- resulto que funcionaba pero solia fallar -- depende como uno hace el clic -- ahora
        //pruebo el ListSelectionListener (osea cuando se encuentra seleccionada) parece que funciona bien
        TablaMaterias.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int selectedRow = TablaMaterias.getSelectedRow();
                    if (selectedRow != -1) {
                        Alumno selectedAlumno = (Alumno) jCBSeleccionAlumno.getSelectedItem();
                        idAlumno = selectedAlumno.getIdAlumno();
                        idMateria = (Integer) TablaMaterias.getValueAt(selectedRow, 0);
                    }
                }
            }
        });

        try {
            cargarCombo();
        } catch (ClassNotFoundException ex) {
            Utilidades.mostrarError(ex,this);
        } catch (SQLException ex) {
            Utilidades.mostrarError(ex,this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLSeleccionAlumno = new javax.swing.JLabel();
        jCBSeleccionAlumno = new javax.swing.JComboBox<>();
        jLListadoMaterias = new javax.swing.JLabel();
        jRBMInscriptas = new javax.swing.JRadioButton();
        jRBMNoInscriptas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMaterias = new javax.swing.JTable();
        jBInscribir = new javax.swing.JButton();
        jBAnularInscripcion = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 51));
        setClosable(true);
        setTitle("Formulario de Inscripcion");

        jLSeleccionAlumno.setForeground(new java.awt.Color(0, 0, 0));
        jLSeleccionAlumno.setText("Seleccione un alumno :");

        jCBSeleccionAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSeleccionAlumnoActionPerformed(evt);
            }
        });

        jLListadoMaterias.setForeground(new java.awt.Color(0, 0, 0));
        jLListadoMaterias.setText("Listado de Materias");

        jRBMInscriptas.setBackground(new java.awt.Color(0, 51, 51));
        jRBMInscriptas.setForeground(new java.awt.Color(0, 0, 0));
        jRBMInscriptas.setText("Materias Inscriptas");
        jRBMInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBMInscriptasActionPerformed(evt);
            }
        });

        jRBMNoInscriptas.setBackground(new java.awt.Color(0, 51, 51));
        jRBMNoInscriptas.setForeground(new java.awt.Color(0, 0, 0));
        jRBMNoInscriptas.setText("Materias no Inscriptas");
        jRBMNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBMNoInscriptasActionPerformed(evt);
            }
        });

        TablaMaterias.setForeground(new java.awt.Color(0, 0, 0));
        TablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMateriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaMaterias);

        jBInscribir.setText("Inscribir");
        jBInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInscribirActionPerformed(evt);
            }
        });

        jBAnularInscripcion.setText("Anular Inscripcion");
        jBAnularInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnularInscripcionActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLSeleccionAlumno)
                        .addGap(36, 36, 36)
                        .addComponent(jCBSeleccionAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jRBMInscriptas)
                        .addGap(143, 143, 143)
                        .addComponent(jRBMNoInscriptas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLListadoMaterias))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBInscribir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAnularInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jBSalir)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCBSeleccionAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSeleccionAlumno))
                .addGap(27, 27, 27)
                .addComponent(jLListadoMaterias)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRBMNoInscriptas)
                    .addComponent(jRBMInscriptas))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBInscribir)
                    .addComponent(jBAnularInscripcion)
                    .addComponent(jBSalir))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBMNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBMNoInscriptasActionPerformed
        selectedAlumno = (Alumno) jCBSeleccionAlumno.getSelectedItem();
        jRBMInscriptas.setSelected(false);
        jRBMNoInscriptas.setSelected(true);

        try {
            modelo.setRowCount(0); // Limpiar la tabla antes de agregar nuevos datos
            cargarTabla(selectedAlumno.getIdAlumno());
        } catch (Exception ex) {
            Utilidades.mostrarError(ex,this);
        }
    }//GEN-LAST:event_jRBMNoInscriptasActionPerformed

    private void jRBMInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBMInscriptasActionPerformed
        selectedAlumno = (Alumno) jCBSeleccionAlumno.getSelectedItem();
        jRBMInscriptas.setSelected(true);
        jRBMNoInscriptas.setSelected(false);
        try {
            modelo.setRowCount(0); // Limpiar la tabla antes de agregar nuevos datos
            cargarTabla(selectedAlumno.getIdAlumno());
        } catch (Exception ex) {
            Utilidades.mostrarError(ex,this);
        }


    }//GEN-LAST:event_jRBMInscriptasActionPerformed

    private void jCBSeleccionAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSeleccionAlumnoActionPerformed
        selectedAlumno = (Alumno) jCBSeleccionAlumno.getSelectedItem();
        if (selectedAlumno != null) {
            // Realiza la carga de la tabla según el ítem seleccionado
            // Por ejemplo, llama a un método cargarTabla(selectedItem)
            modelo.setRowCount(0); // Limpiar la tabla antes de agregar nuevos datos
            try {
                idAlumno = selectedAlumno.getIdAlumno();
                cargarTabla(selectedAlumno.getIdAlumno());
            } catch (Exception ex) {
                Utilidades.mostrarError(ex,this);
            }
        }
    }//GEN-LAST:event_jCBSeleccionAlumnoActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        salirAplicacion();
  
    }//GEN-LAST:event_jBSalirActionPerformed

    private void TablaMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMateriasMouseClicked

    }//GEN-LAST:event_TablaMateriasMouseClicked

    private void jBAnularInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnularInscripcionActionPerformed

        if (idAlumno != 0 && idMateria != 0) {
            try {
                //Anular inscripcion estando el boton inscripto true
                InscripcionDAO inscricionDAO = new InscripcionDAO();
                if (jRBMInscriptas.isSelected() && !jRBMNoInscriptas.isSelected()) {
                    inscricionDAO.borrarInscripcionMateriaAlumno(idAlumno, idMateria, this);
                    modelo.setRowCount(0); // Limpiar la tabla antes de agregar nuevos datos
                    cargarTabla(idAlumno);
                    idMateria = 0;
                    idAlumno = 0;
                } else {
                    JOptionPane.showMessageDialog(this, "Anular la Inscripcion, solo para Materias Inscriptas");
                }
            } catch (ClassNotFoundException ex) {
                Utilidades.mostrarError(ex,this);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "no tiene que tener nota");
            } catch (Exception ex) {
                Utilidades.mostrarError(ex,this);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione por favor, alumno o la materia");
        }
    }//GEN-LAST:event_jBAnularInscripcionActionPerformed

    private void jBInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInscribirActionPerformed

        if (idAlumno != 0 && idMateria != 0) {
            try {
                //Guardar la inscripcion estando el boton inscripto true
                InscripcionDAO inscricionDAO = new InscripcionDAO();

                if (!jRBMInscriptas.isSelected() && jRBMNoInscriptas.isSelected()) {
                    inscricionDAO.guardarInscripcion(idAlumno, idMateria, this);
                } else {
                    JOptionPane.showMessageDialog(this, "Guardar la Inscripcion, solo para Materias NO Inscriptas");
                }
                modelo.setRowCount(0); // Limpiar la tabla antes de agregar nuevos datos
                cargarTabla(idAlumno);
                idMateria = 0;
                idAlumno = 0;
            } catch (ClassNotFoundException ex) {
                Utilidades.mostrarError(ex,this);
                  } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "no tiene que tener nota");
            } catch (Exception ex) {
                Utilidades.mostrarError(ex,this);
                }

        } else {
            JOptionPane.showMessageDialog(this, "Seleccione por favor, alumno o la materia");
        }


    }//GEN-LAST:event_jBInscribirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaMaterias;
    private javax.swing.JButton jBAnularInscripcion;
    private javax.swing.JButton jBInscribir;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<Alumno> jCBSeleccionAlumno;
    private javax.swing.JLabel jLListadoMaterias;
    private javax.swing.JLabel jLSeleccionAlumno;
    private javax.swing.JRadioButton jRBMInscriptas;
    private javax.swing.JRadioButton jRBMNoInscriptas;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {
        //TablaMaterias.addColumn(aColumn);
        modelo.addColumn("Id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Year");
        TablaMaterias.setModel(modelo);
    }

    private void cargarCombo() throws ClassNotFoundException, SQLException {

        AlumnoDAO alumnoDao = new AlumnoDAO();

        Collection<Alumno> alumnos;
        alumnos = new ArrayList<>();

        try {
            alumnos = alumnoDao.listarAlumnos();
        } catch (Exception ex) {
            Utilidades.mostrarError(ex,this);
        }

        // Llena el JComboBox con los valores tipo Alumno
        for (Alumno alumno : alumnos) {
            if (alumno.isEstado()) {
                jCBSeleccionAlumno.addItem(alumno);
            }
            
        }
    }

    private void cargarTabla(int idAlumno) throws Exception {

        InscripcionDAO cursadas = new InscripcionDAO();
        Collection<Materia> listaMaterias = new ArrayList<>(); // Inicialización predeterminada

        if (jRBMInscriptas.isSelected() && !jRBMNoInscriptas.isSelected()) {
            listaMaterias = cursadas.obtenerMateriaCursada(idAlumno);
        } else if (!jRBMInscriptas.isSelected() && jRBMNoInscriptas.isSelected()) {
            listaMaterias = cursadas.obtenerMateriaNOCursada(idAlumno);
        }

        for (Materia tipo : listaMaterias) {
            if (tipo.isEstado()) {
                modelo.addRow(new Object[]{tipo.getIdMateria(), tipo.getNombre(), tipo.getAnio()});

            }
            
        }

    }

    private void salirAplicacion() {
        if (Utilidades.confirmarSalida(this)) {
            dispose();
        }
    }


}
