/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grupo65universidad.Vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author wbasa
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Menu() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEscritorio = new javax.swing.JDesktopPane();
        jLULP = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAlumno = new javax.swing.JMenu();
        jDatosAlumnos = new javax.swing.JMenuItem();
        jMMateria = new javax.swing.JMenu();
        jDatosMaterias = new javax.swing.JMenuItem();
        jMAdministracion = new javax.swing.JMenu();
        jManejoInscripciones = new javax.swing.JMenuItem();
        jManipulacionNotas = new javax.swing.JMenuItem();
        jMConsulta = new javax.swing.JMenu();
        jConsultasMaterias = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jEscritorio.setBackground(new java.awt.Color(0, 51, 51));

        jLULP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo65universidad/Vistas/Imagenes/descarga.jpeg"))); // NOI18N

        jEscritorio.setLayer(jLULP, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jEscritorioLayout = new javax.swing.GroupLayout(jEscritorio);
        jEscritorio.setLayout(jEscritorioLayout);
        jEscritorioLayout.setHorizontalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEscritorioLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLULP)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jEscritorioLayout.setVerticalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEscritorioLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLULP)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jMAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo65universidad/Vistas/Imagenes/student_man_avatar_user_toga_school_university_icon_209294_1.png"))); // NOI18N
        jMAlumno.setText("Alumno");

        jDatosAlumnos.setText("Formulario Alumno");
        jDatosAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDatosAlumnosActionPerformed(evt);
            }
        });
        jMAlumno.add(jDatosAlumnos);

        jMenuBar1.add(jMAlumno);

        jMMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo65universidad/Vistas/Imagenes/education_books_library_icon_149685.png"))); // NOI18N
        jMMateria.setText("Materia");

        jDatosMaterias.setText("Formulario Materia");
        jDatosMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDatosMateriasActionPerformed(evt);
            }
        });
        jMMateria.add(jDatosMaterias);

        jMenuBar1.add(jMMateria);

        jMAdministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo65universidad/Vistas/Imagenes/3700468-archive-document-education-exam-file-test_108747_1.png"))); // NOI18N
        jMAdministracion.setText("Administracion");

        jManejoInscripciones.setText("Manejo de Inscripciones ");
        jManejoInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jManejoInscripcionesActionPerformed(evt);
            }
        });
        jMAdministracion.add(jManejoInscripciones);

        jManipulacionNotas.setText("Manipulacion de Notas");
        jManipulacionNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jManipulacionNotasActionPerformed(evt);
            }
        });
        jMAdministracion.add(jManipulacionNotas);

        jMenuBar1.add(jMAdministracion);

        jMConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo65universidad/Vistas/Imagenes/support_icon-icons.com_55294.png"))); // NOI18N
        jMConsulta.setText("Consultas");

        jConsultasMaterias.setText("Alumnos por Materia");
        jConsultasMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultasMateriasActionPerformed(evt);
            }
        });
        jMConsulta.add(jConsultasMaterias);

        jMenuBar1.add(jMConsulta);

        jMSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo65universidad/Vistas/Imagenes/477A86B10B034C3087ADC368774218B1.png"))); // NOI18N
        jMSalir.setText("Salir");
        jMSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMSalirMouseClicked(evt);
            }
        });
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jEscritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jConultaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConultaEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jConultaEmpleadoActionPerformed

    private void jManejoInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jManejoInscripcionesActionPerformed

        jEscritorio.removeAll();
        jEscritorio.repaint();
        jEscritorio.add(jLULP);

        Inscripciones cargarIncrpcion = new Inscripciones();

// Configurar el tamaño del JInternalFrame
        cargarIncrpcion.setSize(500, 450);

// Calcular el centro del JDesktopPane
        int x = (jEscritorio.getWidth() - cargarIncrpcion.getWidth()) / 2;
        int y = (jEscritorio.getHeight() - cargarIncrpcion.getHeight()) / 2;

// Establecer la ubicación y agregar el JInternalFrame
        cargarIncrpcion.setBounds(x, y, cargarIncrpcion.getWidth(), cargarIncrpcion.getHeight());
        jEscritorio.add(cargarIncrpcion);
        cargarIncrpcion.setVisible(true);
    }//GEN-LAST:event_jManejoInscripcionesActionPerformed

    private void jDatosMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDatosMateriasActionPerformed

        jEscritorio.removeAll();
        jEscritorio.repaint();
        jEscritorio.add(jLULP);

        FormularioMateria cargarMateria = new FormularioMateria();

// Configurar el tamaño del JInternalFrame
        cargarMateria.setSize(400, 300);

// Calcular el centro del JDesktopPane
        int x = (jEscritorio.getWidth() - cargarMateria.getWidth()) / 2;
        int y = (jEscritorio.getHeight() - cargarMateria.getHeight()) / 2;

// Establecer la ubicación y agregar el JInternalFrame
        cargarMateria.setBounds(x, y, cargarMateria.getWidth(), cargarMateria.getHeight());
        jEscritorio.add(cargarMateria);
        cargarMateria.setVisible(true);

    }//GEN-LAST:event_jDatosMateriasActionPerformed

    private void jManipulacionNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jManipulacionNotasActionPerformed

        jEscritorio.removeAll();
        jEscritorio.repaint();
        jEscritorio.add(jLULP);

        ActualizacionNotas cargarNotas = new ActualizacionNotas();

// Configurar el tamaño del JInternalFrame
        cargarNotas.setSize(500, 300);

// Calcular el centro del JDesktopPane
        int x = (jEscritorio.getWidth() - cargarNotas.getWidth()) / 2;
        int y = (jEscritorio.getHeight() - cargarNotas.getHeight()) / 2;

// Establecer la ubicación y agregar el JInternalFrame
        cargarNotas.setBounds(x, y, cargarNotas.getWidth(), cargarNotas.getHeight());
        jEscritorio.add(cargarNotas);
        cargarNotas.setVisible(true);

    }//GEN-LAST:event_jManipulacionNotasActionPerformed

    private void jConsultasMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultasMateriasActionPerformed

        jEscritorio.removeAll();
        jEscritorio.repaint();
        jEscritorio.add(jLULP);

        ConsultaAlumnosxMateria alumnosxMateria = new ConsultaAlumnosxMateria();

// Configurar el tamaño del JInternalFrame
        alumnosxMateria.setSize(400, 300);

// Calcular el centro del JDesktopPane
        int x = (jEscritorio.getWidth() - alumnosxMateria.getWidth()) / 2;
        int y = (jEscritorio.getHeight() - alumnosxMateria.getHeight()) / 2;

// Establecer la ubicación y agregar el JInternalFrame
        alumnosxMateria.setBounds(x, y, alumnosxMateria.getWidth(), alumnosxMateria.getHeight());
        jEscritorio.add(alumnosxMateria);
        alumnosxMateria.setVisible(true);

    }//GEN-LAST:event_jConsultasMateriasActionPerformed

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed

    }//GEN-LAST:event_jMSalirActionPerformed

    private void jDatosAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDatosAlumnosActionPerformed

        jEscritorio.removeAll();
        jEscritorio.repaint();
        jEscritorio.add(jLULP);
        FormularioAlumno cargarAlumnoProbandoVista = new FormularioAlumno();

        // Configurar el tamaño del JInternalFrame
        cargarAlumnoProbandoVista.setSize(400, 300);

        // Calcular el centro del JDesktopPane
        int x = (jEscritorio.getWidth() - cargarAlumnoProbandoVista.getWidth()) / 2;
        int y = (jEscritorio.getHeight() - cargarAlumnoProbandoVista.getHeight()) / 2;

        // Establecer la ubicación y agregar el JInternalFrame
        cargarAlumnoProbandoVista.setBounds(x, y, cargarAlumnoProbandoVista.getWidth(), cargarAlumnoProbandoVista.getHeight());
        jEscritorio.add(cargarAlumnoProbandoVista);
        cargarAlumnoProbandoVista.setVisible(true);


    }//GEN-LAST:event_jDatosAlumnosActionPerformed

    private void jMSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMSalirMouseClicked
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_jMSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jConsultasMaterias;
    private javax.swing.JMenuItem jDatosAlumnos;
    private javax.swing.JMenuItem jDatosMaterias;
    private javax.swing.JDesktopPane jEscritorio;
    private javax.swing.JLabel jLULP;
    private javax.swing.JMenu jMAdministracion;
    private javax.swing.JMenu jMAlumno;
    private javax.swing.JMenu jMConsulta;
    private javax.swing.JMenu jMMateria;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenuItem jManejoInscripciones;
    private javax.swing.JMenuItem jManipulacionNotas;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    private void salir() {
        int respuesta = JOptionPane.showConfirmDialog(this, "Estas seguro que "
                + "quieres salir?", "Salir de la aplicacion", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }
}
